name: Node.js CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean npm cache and reinstall dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install
          npx update-browserslist-db@latest --update-db

      - name: Run linter and tests
        run: |
          npm run lint
          npm test
